Check params from schema
skbkontur/perl-jsonschema-validator pull request #30
Opened 2022-06-28 20:52 UTC by ehuelsmann

When the schema specifies that there are requirements for header/cookie/etc parameters, and these parameters aren't provided in the instance data, return an error indicating this data is required for schema validation.

This commit unveils a condition that wasn't tested by the tests before: The validation of the `X-SERVER-sUPPoRTED-vERSIONs` header. However, its validation runs into issue #12 because its type (and test data) are of type `array`.

@avkhozov could you please indicate how you want me to resolve the currently failing tests? By changing the test case to a string? Or does #12 need to be fixed before this PR is acceptable at all? Or ...?

I've created this PR as a draft PR pending my fixes which I expect to be doing based on responses to the above questions.

2022-08-18 18:49 UTC, Logioniz commented
@ehuelsmann, if I understand correctly, then this test conflicts with the unsolved problem #12. Maybe it would be better if you replace the header value with the array type to a value with the number type in this PR?

2022-08-22 04:05 UTC, uid66 requested changes

2022-08-22 17:50 UTC, ehuelsmann commented on lib/JSONSchema/Validator/OAS30.pm
> +            push @{$ctx->{errors}}, error(message => qq{schema specifies '$type' parameters, but '$type' parameter missing in instance data});
Added.

2022-08-22 17:53 UTC, ehuelsmann commented
> @ehuelsmann, if I understand correctly, then this test conflicts with the unsolved problem #12. Maybe it would be better if you replace the header value with the array type to a value with the number type in this PR?

@Logioniz fortunately, #12 is fixed on the main branch now, so I was able to fix the PR.

2022-08-23 02:26 UTC, uid66 approved these changes

2022-08-23 05:49 UTC, doojonio approved these changes

2022-08-23 05:51 UTC, avkhozov approved these changes

2022-08-23 05:52 UTC, merged